target_repository:
  HTTPS: https://github.com/pykeen/pykeen.git
  # OPTIONAL, checkout a particular branch or a tag
  checkout: master
  # OPTIONAL, define installing package extras
  install_extras: lightning
  # OPTIONAL, install additional requirements from a file
  # requirements_file: requirements.txt
  # copy some  test from the target repository
  copy_tests:
    - tests/test_lightning.py

contact:
  slack:
    # Max Berrendorf
    - U03DAAVMLSH
  email: []

# OPTIONAL, running before installing your project
# WARNING: this is custom for given OS, we do not manage any inter OS compatibility
#before_install:
#  - pip install Cython==3.56

# OPTIONAL, if any installation require some env. variables
#env:
#  HOROVOD_BUILD_ARCH_FLAGS: "-mfma"
#  # HOROVOD_WITHOUT_MXNET: 1
#  # HOROVOD_WITHOUT_TENSORFLOW: 1

dependencies:
  - name: pytorch-lightning
    HTTPS: https://github.com/PyTorchLightning/pytorch-lightning.git
    checkout: release/latest
    # install_extras: all
#  - name: Cython
#    checkout: 0.29.24

# OPTIONAL, running before installing your project
# WARNING: this is custom for given OS, we do not manage any inter OS compatibility
#before_test:
#  - wget https://pl-flash-data.s3.amazonaws.com/titanic.zip

testing:
  dirs:
    - tests/
#  # OPTIONAL, additional pytest arguments
#  pytest_args: --strict

runtimes:
  - {os: "ubuntu-20.04", python-version: "3.10"}
  - {os: "macOS-10.15", python-version: "3.9"}
  - {os: "windows-2019", python-version: "3.8"}
