target_repository:
  HTTPS: https://github.com/PyTorchLightning/lightning-transformers.git
  # checkout a particular branch or a tag
  checkout: master
  # define installing package extras
  install_extras: extra
  # copy some  test from the target repository
  copy_tests:
    - tests
    - examples
    - conf

contact:
  slack:
    # Sean Narenthiran
    - U01BULUS2BG

dependencies:
  - name: pytorch-lightning
    HTTPS: https://github.com/Lightning-AI/lightning.git
    checkout: master
    # install_extras: all

testing:
  dirs:
    - tests

runtimes:
  - {os: "ubuntu-20.04", python-version: "3.8"}
