trigger:
  branches:
    include: ["main"]
pr:
  branches:
    include: ["main"]
  autoCancel: true
  drafts: true

schedules:
  - cron: "0 0 * * *" # At the end of every day
    displayName: Daily midnight duty
    branches:
      include: ["main"]

jobs:
- template: testing-template.yml
  parameters:
    configs:
    - "PyTorchLightning/metrics_pl-develop.yaml"
    - "PyTorchLightning/metrics_pl-release.yaml"
    - "PyTorchLightning/flash_pl-develop.yaml"
    - "PyTorchLightning/flash_pl-release.yaml"
    # NNI
    - "configs/nni/nni-develop.yaml"
