trigger:
  branches:
    include: ["main"]
pr:
  branches:
    include: ["main"]
  autoCancel: true
  drafts: true

schedules:
  - cron: "0 0 * * *" # At the end of every day
    displayName: Daily midnight duty
    branches:
      include: ["main"]

jobs:
- template: testing-template.yml
  parameters:
    configs:
    - "Lightning-AI/metrics_pl-develop.yaml"
    - "Lightning-AI/metrics_pl-release.yaml"
    - "Lightning-AI/flash_pl-develop.yaml"
    - "Lightning-AI/flash_pl-release.yaml"
    - "microsoft/deepspeed-release.yaml"
