target_repository:
  HTTPS: https://github.com/Lightning-AI/lightning-bolts.git
  # checkout a particular branch or a tag
  checkout: master
  # define installing package extras
  install_extras: extra
  # copy some  test from the target repository
  copy_tests:
    - tests

contact:
  slack:
    - UR9FXE6QG  # borda

env:
  # let's limit the installation only to Pytorch-Lightning
  PACKAGE_NAME: pytorch

dependencies:
  - name: pytorch-lightning
    HTTPS: https://github.com/Lightning-AI/lightning.git
    checkout: master
    # install_extras: all
  - name: torchmetrics
    HTTPS: https://github.com/Lightning-AI/metrics.git
    checkout: master

testing:
  dirs:
    - tests

runtimes:
  - {os: "ubuntu-20.04", python: "3.8"}
