target_repository:
  HTTPS: https://github.com/Lightning-AI/metrics.git
  # checkout a particular branch or a tag
  checkout: master
  # define installing package extras
  install_extras: all
  # copy some  test from the target repository
  copy_tests:
    - tests/integrations

contact:
  slack:
    # Nicki Skafte
    - USZ6EQ8A2

env:
  # let's limit the installation only to Pytorch-Lightning
  PACKAGE_NAME: pytorch

dependencies:
  - name: pytorch-lightning
    HTTPS: https://github.com/Lightning-AI/lightning.git
    checkout: release/stable
    # install_extras: all

runtimes:
  - {os: "ubuntu-22.04", python: "3.10"}
  - {os: "macOS-12", python: "3.9"}
  - {os: "windows-2022", python: "3.8"}
