target_repository:
  HTTPS: https://github.com/microsoft/nni.git
  # checkout a particular branch or a tag
  checkout: master
  # NNI needs custom install. `python setup.py install` or `pip install .` won't work.
  install_command: |
    if [ -x "$(command -v nvidia-smi)" ]; then
      echo 'GPU exist, use recommended_gpu.txt'
      mv dependencies/recommended_gpu.txt dependencies/recommended.txt;
    fi
    echo '===== develop ====='
    pip install -r dependencies/develop.txt
    echo '===== required ====='
    pip install -r dependencies/required.txt
    echo '===== required extra ====='
    pip install -r dependencies/required_extra.txt
    echo '===== recommended ====='
    pip install -r dependencies/recommended.txt
    echo '===== running develop install ====='
    python setup.py develop
  # development build. Cannot remove dir
  remove_dir: false
  # copy some tests from the target repository
  copy_tests:
    # only retiarii uses pytorch-lightning for now
    # might add more in future
    - test/ut/retiarii
    - test/ut/__init__.py

dependencies:
  - name: pytorch-lightning
    HTTPS: https://github.com/PyTorchLightning/pytorch-lightning.git
    checkout: release/1.5.x
    install_extras: loggers

testing:
  dirs:
    - test/ut

runtimes:
  - {os: "ubuntu-latest", python-version: "3.8"}

