target_repository:
  HTTPS: https://github.com/microsoft/nii.git
  # checkout a particular branch or a tag
  checkout: master
  # NNI needs custom install. `python setup.py install` or `pip install .` won't work.
  install_command: export NNI_RELEASE=`git describe --tags --abbrev=0` && python test/vso_tools/build_wheel.py $(NNI_RELEASE) && pip install dist/*.whl
  # copy some tests from the target repository
  copy_tests:
    # only retiarii uses pytorch-lightning for now
    # might add more in future
    - test/ut/retiarii
    - test/ut/__init__.py

dependencies:
  - name: pytorch-lightning
    HTTPS: https://github.com/PyTorchLightning/pytorch-lightning.git
    checkout: master
    # install_extras: all
  - name: torchmetrics
    HTTPS: https://github.com/PyTorchLightning/metrics.git
    checkout: master
    # install_extras: all

testing:
  dirs:
    - test/ut

runtimes:
  - {os: "ubuntu-latest", python-version: "3.8"}
