target_repository:
  HTTPS: https://github.com/microsoft/nni.git
  # checkout a particular branch or a tag
  checkout: master
  before_install:
    - if [ -x "$(command -v nvidia-smi)" ]; then mv dependencies/recommended_gpu.txt dependencies/recommended.txt; fi
  # NNI needs custom install. `python setup.py install` or `pip install .` won't work.
  install_files:
    - dependencies/develop.txt
    - dependencies/required.txt
    - dependencies/required_extra.txt
    - dependencies/recommended.txt
  install_command: python setup.py develop
  # development build. Cannot remove dir
  remove_dir: false
  # copy some tests from the target repository
  copy_tests:
    # only retiarii uses pytorch-lightning for now
    # might add more in future
    - test/ut/retiarii
    - test/ut/__init__.py

before_install:
  - pip install numpy

dependencies:
  - name: pytorch-lightning
    HTTPS: https://github.com/PyTorchLightning/pytorch-lightning.git
    checkout: release/1.5.x
    install_extras: loggers

testing:
  dirs:
    - test/ut

runtimes:
  - {os: "ubuntu-latest", python-version: "3.8"}
