name: Dump job details
description: save and upload job meta and status

inputs:
  artifact-name:
    description: unique hash or index
    required: true

runs:
  using: "composite"
  steps:

  - uses: ReeganExE/github-action-job-id@v1.0

  - name: Dump details
    run: |
      import os, json
      data = json.loads('''${{ toJSON(matrix) }}''')
      data.update(json.loads('''${{ toJSON(job) }}'''))
      gh_job = "GH_JOB_${{ strategy.job-index }}"
      for n, v in os.environ.items():
        if not n.startswith(gh_job):
          continue
        data[n.replace(f"{gh_job}_", "").lower()] = v
      with open("project-results.json", "w") as fp:
        json.dump(data, fp)
    shell: python

  - name: Show job's meta
    run: cat project-results.json
    shell: bash

  - name: Upload pytest test results
    uses: actions/upload-artifact@v2
    with:
      name: ${{ inputs.artifact-name }}
      path: project-results.json
