source_repository:
  HTTPS: https://github.com/vturrisi/solo-learn.git
  checkout: main
  # OPTIONAL, define installing package extras
  install_extras: umap
  # copy some  test from the target repository
  copy_tests:
    - tests

contact:
  slack:
    # Victor Turrisi
    - U0303D6JSAF

env:
  # let's limit the installation only to Pytorch-Lightning
  PACKAGE_NAME: pytorch

dependencies:
  - name: pytorch-lightning
    HTTPS: https://github.com/Lightning-AI/lightning.git
    checkout: release/LTS
    # install_extras: all
  - name: torchmetrics
    HTTPS: https://github.com/Lightning-AI/metrics.git
    checkout: release/stable
  - name: lightning-bolts
    HTTPS: https://github.com/Lightning-AI/lightning-bolts.git
    checkout: release/stable
  - name: h5py

testing:
  dirs:
    - tests/args
    - tests/losses
    - tests/methods
    - tests/utils

runtimes:
  - { os: "ubuntu-20.04", python: "3.9" }
  - { os: "macOS-12", python: "3.8" }
  - { os: "windows-2019", python: "3.8" }
