name: CI action schema
on: # Trigger the workflow on push or pull request, but only for the default branch
  push: {}
  pull_request:
    branches: [main]

jobs:
  validate-schema:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pkg
        run: |
          pip install "check-jsonschema>=0.10"

      - name: GH Workflows
        run: |
          check-jsonschema .github/workflows/*.yml --builtin-schema "github-workflows"
